# Generated by Django 3.0.6 on 2020-05-29 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mood', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2')], help_text='0开心，1平淡无奇，2难过', max_length=4, verbose_name='心情')),
                ('content', models.TextField(max_length=300, verbose_name='消息内容')),
                ('type', models.CharField(choices=[('0', '0'), ('1', '1')], help_text='0私人花园信息，1公共花园信息', max_length=4, verbose_name='类型')),
                ('anonymity', models.CharField(choices=[('0', '0'), ('1', '1')], help_text='0不匿名，1匿名（私人花园都不匿名）', max_length=4, verbose_name='类型')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发表时间')),
                ('user', models.ForeignKey(help_text='消息需要绑定一个用户', on_delete=django.db.models.deletion.CASCADE, related_name='message', to=settings.AUTH_USER_MODEL, verbose_name='对应用户')),
            ],
            options={
                'verbose_name': '心情花园',
                'verbose_name_plural': '心情花园',
                'ordering': ('create_time',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=300, verbose_name='消息内容')),
                ('anonymity', models.CharField(choices=[('0', '0'), ('1', '1')], help_text='0不匿名，1匿名（私人花园都不匿名）', max_length=4, verbose_name='类型')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发表时间')),
                ('message', models.ForeignKey(help_text='消息需要绑定一个用户', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='psygarden.Message', verbose_name='对应用户')),
                ('user', models.ForeignKey(help_text='消息需要绑定一个用户', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='对应用户')),
            ],
            options={
                'verbose_name': '心情花园评论',
                'verbose_name_plural': '心情花园评论',
                'ordering': ('create_time',),
            },
        ),
    ]
