# Generated by Django 3.0.6 on 2020-05-29 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psygarden', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('create_time',), 'verbose_name': '消息评论', 'verbose_name_plural': '消息评论'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('create_time',), 'verbose_name': '心情消息', 'verbose_name_plural': '心情消息'},
        ),
    ]
