# Generated by Django 3.0.6 on 2020-05-29 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200529_1543'),
        ('psygarden', '0002_auto_20200529_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(help_text='消息需要绑定一个用户', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='user.User', verbose_name='对应用户'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(help_text='消息需要绑定一个用户', on_delete=django.db.models.deletion.CASCADE, related_name='message', to='user.User', verbose_name='对应用户'),
        ),
    ]
