# Generated by Django 2.2.4 on 2020-05-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_auto_20200526_1655"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="idcard",
            field=models.CharField(blank=True, help_text="用户唯一标识之一", max_length=18, null=True, unique=True, verbose_name="身份证号码"),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="未命名", max_length=8, verbose_name="真实姓名"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_nickname",
            field=models.CharField(default="未命名", max_length=30, verbose_name="昵称"),
        ),
    ]
