# Generated by Django 2.2.4 on 2020-05-27 11:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_auto_20200527_1110"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultant",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("grade", models.CharField(help_text="比如二级心理咨询师", max_length=20, verbose_name="咨询师等级")),
                ("expertise", models.CharField(help_text="比如善于处理青少年问题", max_length=20, verbose_name="专长")),
                ("training", models.CharField(help_text="比如中科院心理所医学与心理咨询治疗专业硕士研究生", max_length=20, verbose_name="专业")),
                ("qq", models.CharField(max_length=16, verbose_name="咨询师QQ")),
                ("create_time", models.DateTimeField(default=django.utils.timezone.now, verbose_name="注册时间")),
                ("user", models.ForeignKey(blank=True, help_text="咨询师需要绑定一个用户", on_delete=django.db.models.deletion.CASCADE, related_name="user", to="user.User", verbose_name="对应用户")),
            ],
            options={
                "verbose_name": "咨询师信息",
                "verbose_name_plural": "咨询师信息",
                "ordering": ("create_time",),
            },
        ),
    ]
