# Generated by Django 3.0.6 on 2020-05-27 21:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_consultant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='create_time',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='files/avatar/default.jpg', max_length=300, null=True, verbose_name='头像绝对路径'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.CharField(blank=True, default=0, max_length=20, null=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, help_text='用户唯一标识之一', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('1[345678]\\d{9}$', message='请输入正确的电话号码！')], verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('2', '2'), ('1', '1'), ('0', '0')], default='0', help_text='0未知，1男，2女', max_length=4, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.CharField(choices=[('2', '2'), ('1', '1'), ('0', '0')], default='0', help_text='0未验证，1已验证普通用户，2咨询师', max_length=4, verbose_name='用户验证状态'),
        ),
    ]
