# Generated by Django 3.0.6 on 2020-05-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200527_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='training',
            field=models.CharField(help_text='比如中科院心理所医学与心理咨询治疗专业硕士研究生', max_length=40, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.CharField(blank=True, default='1590736459', max_length=20, null=True, verbose_name='注册时间'),
        ),
    ]
