# Generated by Django 3.0.6 on 2020-05-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200529_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.CharField(blank=True, default='1590737497', max_length=20, null=True, verbose_name='注册时间'),
        ),
    ]
