# Generated by Django 3.0.6 on 2020-05-29 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20200529_1542'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='consultant',
            name='user',
            field=models.ForeignKey(blank=True, help_text='咨询师需要绑定一个用户', on_delete=django.db.models.deletion.CASCADE, related_name='consultant', to='user.User', verbose_name='对应用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.CharField(blank=True, default='1590738205', max_length=20, null=True, verbose_name='注册时间'),
        ),
    ]
