# Generated by Django 2.2.4 on 2020-04-29 11:44

import content.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Articles",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, verbose_name="文章名称")),
                ("content", models.CharField(blank=True, max_length=300, verbose_name="文章简介")),
                ("url", models.URLField(max_length=100, null=True, verbose_name="url路径")),
                ("register_time", models.DateTimeField(default=django.utils.timezone.now, verbose_name="上传时间")),
            ],
            options={
                "ordering": ("register_time",),
            },
        ),
        migrations.CreateModel(
            name="Consultant",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, verbose_name="咨询师姓名")),
                ("content", models.CharField(blank=True, max_length=300, verbose_name="咨询师简介")),
                ("telephone", models.CharField(blank=True, max_length=11, verbose_name="咨询师电话")),
                ("QQ", models.CharField(blank=True, max_length=16, verbose_name="咨询师QQ")),
                ("register_time", models.DateTimeField(default=django.utils.timezone.now, verbose_name="注册时间")),
            ],
            options={
                "ordering": ("register_time",),
            },
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, verbose_name="讲座名称")),
                ("content", models.CharField(blank=True, max_length=300, verbose_name="讲座简介")),
                ("time", models.DateTimeField(default=django.utils.timezone.now, verbose_name="开始时间")),
            ],
            options={
                "ordering": ("time",),
            },
        ),
        migrations.CreateModel(
            name="PsyTest",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, verbose_name="心理测试名称")),
                ("content", models.CharField(blank=True, max_length=300, verbose_name="测试简介")),
                ("url", models.URLField(max_length=100, null=True, verbose_name="url路径")),
                ("register_time", models.DateTimeField(default=django.utils.timezone.now, verbose_name="上传时间")),
            ],
            options={
                "ordering": ("register_time",),
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=20, verbose_name="资源名称")),
                ("content", models.CharField(blank=True, max_length=300, verbose_name="资源简介")),
                ("resource", models.FileField(help_text="直接上传到服务器，名称中不要有中文", upload_to=content.models.Resource.resource_path, verbose_name="资源上传")),
                ("register_time", models.DateTimeField(default=django.utils.timezone.now, verbose_name="上传时间")),
            ],
            options={
                "ordering": ("register_time",),
            },
        ),
    ]
