# Generated by Django 2.2.4 on 2020-04-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articles",
            options={"ordering": ("register_time",), "verbose_name": "好文共赏", "verbose_name_plural": "好文共赏"},
        ),
        migrations.AlterModelOptions(
            name="consultant",
            options={"ordering": ("register_time",), "verbose_name": "一键咨询", "verbose_name_plural": "一键咨询"},
        ),
        migrations.AlterModelOptions(
            name="lecture",
            options={"ordering": ("time",), "verbose_name": "名家讲座", "verbose_name_plural": "名家讲座"},
        ),
        migrations.AlterModelOptions(
            name="psytest",
            options={"ordering": ("register_time",), "verbose_name": "趣味测试", "verbose_name_plural": "趣味测试"},
        ),
        migrations.AlterModelOptions(
            name="resource",
            options={"ordering": ("register_time",), "verbose_name": "书籍资源", "verbose_name_plural": "书籍资源"},
        ),
    ]
