# Generated by Django 2.2.4 on 2020-05-27 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("topic", models.TextField(max_length=300, verbose_name="题目")),
                ("create_time", models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name="上传时间")),
                ("tend", models.CharField(choices=[("0", "0"), ("1", "1"), ("2", "2"), ("3", "3")], help_text="0内向/外向，1实感/直觉，2思考/情感，3判断/知觉", max_length=4, verbose_name="倾向")),
                ("choose1", models.CharField(help_text="注意，选项1对应左侧倾向", max_length=30, verbose_name="选项1文本")),
                ("choose2", models.CharField(help_text="注意，选项2对应右侧倾向", max_length=30, verbose_name="选项2文本")),
            ],
            options={
                "verbose_name": "测试题目",
                "verbose_name_plural": "测试题目",
                "ordering": ("id",),
            },
        ),
    ]
