# Generated by Django 2.2.4 on 2020-05-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("psytest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="choose1",
            field=models.TextField(help_text="注意，选项1对应左侧倾向", max_length=100, verbose_name="选项1"),
        ),
        migrations.AlterField(
            model_name="questions",
            name="choose2",
            field=models.TextField(help_text="注意，选项2对应右侧倾向", max_length=100, verbose_name="选项2"),
        ),
        migrations.AlterField(
            model_name="questions",
            name="topic",
            field=models.TextField(max_length=100, verbose_name="题目"),
        ),
    ]
